export const GREY = '#ddd'
export const RED = 'red'

export let circlesDefault = [
  [ // 一行
    {x: 0, y: 4, z: 4, color: GREY},  // 一个点
  ],
  [
    {x: 1, y: 3, z: 4, color: GREY},
    {x: 1, y: 4, z: 5, color: GREY},
  ],
  [
    {x: 2, y: 2, z: 4, color: GREY},
    {x: 2, y: 3, z: 5, color: GREY},
    {x: 2, y: 4, z: 6, color: GREY},
  ],
  [
    {x: 3, y: 1, z: 4, color: GREY},
    {x: 3, y: 2, z: 5, color: GREY},
    {x: 3, y: 3, z: 6, color: GREY},
    {x: 3, y: 4, z: 7, color: GREY},
  ],
  [
    {x: 4, y: -4, z: 0, color: GREY},
    {x: 4, y: -3, z: 1, color: GREY},
    {x: 4, y: -2, z: 2, color: GREY},
    {x: 4, y: -1, z: 3, color: GREY},
    {x: 4, y: 0, z: 4, color: GREY},
    {x: 4, y: 1, z: 5, color: GREY},
    {x: 4, y: 2, z: 6, color: GREY},
    {x: 4, y: 3, z: 7, color: GREY},
    {x: 4, y: 4, z: 8, color: GREY},
    {x: 4, y: 5, z: 9, color: GREY},
    {x: 4, y: 6, z: 10, color: GREY},
    {x: 4, y: 7, z: 11, color: GREY},
    {x: 4, y: 8, z: 12, color: GREY},
  ],
  [
    {x: 5, y: -4, z: 1, color: GREY},
    {x: 5, y: -3, z: 2, color: GREY},
    {x: 5, y: -2, z: 3, color: GREY},
    {x: 5, y: -1, z: 4, color: GREY},
    {x: 5, y: 0, z: 5, color: GREY},
    {x: 5, y: 1, z: 6, color: GREY},
    {x: 5, y: 2, z: 7, color: GREY},
    {x: 5, y: 3, z: 8, color: GREY},
    {x: 5, y: 4, z: 9, color: GREY},
    {x: 5, y: 5, z: 10, color: GREY},
    {x: 5, y: 6, z: 11, color: GREY},
    {x: 5, y: 7, z: 12, color: GREY},
  ],
  [
    {x: 6, y: -4, z: 2, color: GREY},
    {x: 6, y: -3, z: 3, color: GREY},
    {x: 6, y: -2, z: 4, color: GREY},
    {x: 6, y: -1, z: 5, color: GREY},
    {x: 6, y: 0, z: 6, color: GREY},
    {x: 6, y: 1, z: 7, color: GREY},
    {x: 6, y: 2, z: 8, color: GREY},
    {x: 6, y: 3, z: 9, color: GREY},
    {x: 6, y: 4, z: 10, color: GREY},
    {x: 6, y: 5, z: 11, color: GREY},
    {x: 6, y: 6, z: 12, color: GREY},
  ],
  [
    {x: 7, y: -4, z: 3, color: GREY},
    {x: 7, y: -3, z: 4, color: GREY},
    {x: 7, y: -2, z: 5, color: GREY},
    {x: 7, y: -1, z: 6, color: GREY},
    {x: 7, y: 0, z: 7, color: GREY},
    {x: 7, y: 1, z: 8, color: GREY},
    {x: 7, y: 2, z: 9, color: GREY},
    {x: 7, y: 3, z: 10, color: GREY},
    {x: 7, y: 4, z: 11, color: GREY},
    {x: 7, y: 5, z: 12, color: GREY},
  ],
  [
    {x: 8, y: -4, z: 4, color: GREY},
    {x: 8, y: -3, z: 5, color: GREY},
    {x: 8, y: -2, z: 6, color: GREY},
    {x: 8, y: -1, z: 7, color: GREY},
    {x: 8, y: 0, z: 8, color: GREY},
    {x: 8, y: 1, z: 9, color: GREY},
    {x: 8, y: 2, z: 10, color: GREY},
    {x: 8, y: 3, z: 11, color: GREY},
    {x: 8, y: 4, z: 12, color: GREY},
  ],
  [
    {x: 9, y: -5, z: 4, color: GREY},
    {x: 9, y: -4, z: 5, color: GREY},
    {x: 9, y: -3, z: 6, color: GREY},
    {x: 9, y: -2, z: 7, color: GREY},
    {x: 9, y: -1, z: 8, color: GREY},
    {x: 9, y: 0, z: 9, color: GREY},
    {x: 9, y: 1, z: 10, color: GREY},
    {x: 9, y: 2, z: 11, color: GREY},
    {x: 9, y: 3, z: 12, color: GREY},
    {x: 9, y: 4, z: 13, color: GREY},
  ],
  [
    {x: 10, y: -6, z: 4, color: GREY},
    {x: 10, y: -5, z: 5, color: GREY},
    {x: 10, y: -4, z: 6, color: GREY},
    {x: 10, y: -3, z: 7, color: GREY},
    {x: 10, y: -2, z: 8, color: GREY},
    {x: 10, y: -1, z: 9, color: GREY},
    {x: 10, y: 0, z: 10, color: GREY},
    {x: 10, y: 1, z: 11, color: GREY},
    {x: 10, y: 2, z: 12, color: GREY},
    {x: 10, y: 3, z: 13, color: GREY},
    {x: 10, y: 4, z: 14, color: GREY},
  ],
  [
    {x: 11, y: -7, z: 4, color: GREY},
    {x: 11, y: -6, z: 5, color: GREY},
    {x: 11, y: -5, z: 6, color: GREY},
    {x: 11, y: -4, z: 7, color: GREY},
    {x: 11, y: -3, z: 8, color: GREY},
    {x: 11, y: -2, z: 9, color: GREY},
    {x: 11, y: -1, z: 10, color: GREY},
    {x: 11, y: 0, z: 11, color: GREY},
    {x: 11, y: 1, z: 12, color: GREY},
    {x: 11, y: 2, z: 13, color: GREY},
    {x: 11, y: 3, z: 14, color: GREY},
    {x: 11, y: 4, z: 15, color: GREY},
  ],
  [
    {x: 12, y: -8, z: 4, color: GREY},
    {x: 12, y: -7, z: 5, color: GREY},
    {x: 12, y: -6, z: 6, color: GREY},
    {x: 12, y: -5, z: 7, color: GREY},
    {x: 12, y: -4, z: 8, color: GREY},
    {x: 12, y: -3, z: 9, color: GREY},
    {x: 12, y: -2, z: 10, color: GREY},
    {x: 12, y: -1, z: 11, color: GREY},
    {x: 12, y: 0, z: 12, color: GREY},
    {x: 12, y: 1, z: 13, color: GREY},
    {x: 12, y: 2, z: 14, color: GREY},
    {x: 12, y: 3, z: 15, color: GREY},
    {x: 12, y: 4, z: 16, color: GREY},
  ],
  [
    {x: 13, y: -4, z: 9, color: GREY},
    {x: 13, y: -3, z: 10, color: GREY},
    {x: 13, y: -2, z: 11, color: GREY},
    {x: 13, y: -1, z: 12, color: GREY},
  ],
  [
    {x: 14, y: -4, z: 10, color: GREY},
    {x: 14, y: -3, z: 11, color: GREY},
    {x: 14, y: -2, z: 12, color: GREY},
  ],
  [
    {x: 15, y: -4, z: 11, color: GREY},
    {x: 15, y: -3, z: 12, color: GREY},
  ],
  [
    {x: 16, y: -4, z: 12, color: GREY},
  ]
]
